export const FETCH_TEAMS = "FETCH_TEAMS"
export const FETCH_TEAM = "FETCH_TEAM"
export const SELECT_TEAM = "SELECT_TEAM"
export const SELECT_TEAMS = "SELECT_TEAMS"
export const CLEAR_TEAMS = "CLEAR_TEAMS"
export const REMOVE_TEAM = "REMOVE_TEAM"
export const FETCH_GAMES = "FETCH_GAMES"

export const NEXT_PAGE = "NEXT_PAGE"
export const SET_PAGE = "SET_PAGE"
export const SET_PAGE_AMOUNT = "SET_PAGE_AMOUNT"
export const SET_PAGE_NAME = "SET_PAGE_NAME"